// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXbM4VFn9x5uEBwIrmpy1cR1JBBZxj8o',
    appId: '1:493520320034:web:ede5ded721754e96b5fc7b',
    messagingSenderId: '493520320034',
    projectId: 'my-cool-project-rl',
    authDomain: 'my-cool-project-rl.firebaseapp.com',
    storageBucket: 'my-cool-project-rl.firebasestorage.app',
    measurementId: 'G-DCE4SXG1FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1zbRHO-evgw6VN5mXWM9b07dXXrolSrM',
    appId: '1:493520320034:android:5922dcd1ee659bf3b5fc7b',
    messagingSenderId: '493520320034',
    projectId: 'my-cool-project-rl',
    storageBucket: 'my-cool-project-rl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBipCNQuyZmW855Baoo6ofDQu2PNzj65nE',
    appId: '1:493520320034:ios:1e63a989787aa064b5fc7b',
    messagingSenderId: '493520320034',
    projectId: 'my-cool-project-rl',
    storageBucket: 'my-cool-project-rl.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBipCNQuyZmW855Baoo6ofDQu2PNzj65nE',
    appId: '1:493520320034:ios:1e63a989787aa064b5fc7b',
    messagingSenderId: '493520320034',
    projectId: 'my-cool-project-rl',
    storageBucket: 'my-cool-project-rl.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaXbM4VFn9x5uEBwIrmpy1cR1JBBZxj8o',
    appId: '1:493520320034:web:d82d2df4ded85f15b5fc7b',
    messagingSenderId: '493520320034',
    projectId: 'my-cool-project-rl',
    authDomain: 'my-cool-project-rl.firebaseapp.com',
    storageBucket: 'my-cool-project-rl.firebasestorage.app',
    measurementId: 'G-3K3EB3E8LJ',
  );
}
